apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: hcap-showcase-templates
  description: A collection of Customized Backstage templates for Adoption Team workshop
spec:
  type: url
  targets:
    - https://github.com/redhat-apac-stp/rhdh-demo-template/blob/main/scaffolder-templates/poi-backend/template.yaml
    - https://github.com/redhat-apac-stp/rhdh-demo-template/blob/main/scaffolder-templates/poi-gateway/template.yaml
    - https://github.com/redhat-apac-stp/rhdh-demo-template/blob/main/scaffolder-templates/poi-map/template.yaml
